### ISSUE TITLE
NAV and CUBEMAPS closes and opens the game

### ISSUE THREAD

**Issue by resray** [ruarai/CompilePal#138]
When compiling with the NAV command, it will build the nav meshes, so it will open the game. When finished, it will close the game. Pretty simple right? But when adding the CUBEMAPS command to compile settings it will repeat the same process, which means the game will open, close, open and close again, making compiling really slow. A quick fix is to only tell the command to only open the game, because 2 instances of TF2 can't be running together, so only one will stay. Thanks.

**Comment by maxdup** [comment]
We're using launch options to run commands such as buildcubemaps and nav_generate. We don't actually have access to the game console. This method is limited, which is why we need to do those separately. For a ldr+hdr compile, Compilepal might even launch the game up to 3 times. This is slow, but it's still hella faster than doing it by hand.

Unless there's a VAC safe way of taking control of the game client and run these commands, this will not be possible.
