### ISSUE TITLE
PropCombined assets texture doesn't get packed

### ISSUE THREAD

**Issue by Oskmos** [ruarai/CompilePal#146]
**Describe the bug**
If I successfully combine ALL existing instances of one specific asset. And that asset has its own texture that is not used by any other assets. The texture does not get packed by compilePal

if I disable propcombine on one of those instances. compilepal packs the texture.

**Expected behavior**
I expect it to find and pack the texture used by the prop created by PropCombine

**Comment by maxdup** [comment]
hey I'm unlikely going to fix this myself but I figured I'd chime in since this hasn't had a reply yet.

I confirm this issue is an oversight.

How we're going to need to fix that is to extract the pak file and analyse models already present in the pak file.
This is something we already do for vmt files:  https://github.com/ruarai/CompilePal/blob/master/CompilePalX/Compilers/BSPPack/AssetUtils.cs#L485

We only need to do the same thing for .mdl

**Comment by Exactol** [comment]
Closing this since Counter Strike is now on Source 2. If you think this is still needed feel free to reopen the issue
