### ISSUE TITLE
App crashes before compilation can begin.

### ISSUE THREAD

**Issue by hammk** [ruarai/CompilePal#197]
**Compile Pal Version**
V027

**Describe the bug**
Before any work is done with compiling, the application crashes

**Steps to reproduce**
Compile a map.

**Expected behavior**
The map compilation begins and proceeds to the finish.

**Debug.log**
[debug.log](https://github.com/ruarai/CompilePal/files/10867603/debug.log)
The log mentions a Windows user account name, 10zil.

**Crash logs**
No logs added to CrashLogs.

**Additional context**
The map in question was made with JBmod in mind and its respective build tools; otherwise wholly compatible with Source 2013MP.

**Comment by Exactol** [comment]
Can you try the latest prerelease? On Mar 1, 2023, at 11:36 PM, hamm ***@***.***> wrote:﻿
Compile Pal Version
V027
Describe the bug
Before any work is done with compiling, the application crashes
Steps to reproduce
Compile a map.
Expected behavior
The map compilation begins and proceeds to the finish.
Debug.log
debug.log
The log mentions a Windows user account name, 10zil.
Crash logs
No logs added to CrashLogs.
Additional context
The map in question was made with JBmod in mind and its respective build tools; otherwise wholly compatible with Source 2013MP.

**Comment by hammk** [comment]
> Can you try the latest prerelease? https://github.com/ruarai/CompilePal/releases/tag/v027.35

The prerelease did not have this issue, thanks!
