### ISSUE TITLE
Can't even run it.

### ISSUE THREAD

**Issue by SARCASMISH** [ruarai/CompilePal#232]
**Compile Pal Version**
0.28
**Describe the bug**
Compile Pal crashes instantly on launch.

**Steps to reproduce**
Run CompilePalX.exe

**Expected behavior**
I excepted Compile Pal to run normally.

**Debug.log**
[debug.log](https://github.com/ruarai/CompilePal/files/14001264/debug.log)

**Crash logs**
[2024-01-21T13-05-52.txt](https://github.com/ruarai/CompilePal/files/14001265/2024-01-21T13-05-52.txt)

**Additional context**
It seems that the program can't find GameConfig.txt file in "Half-Life 2 Beta" folder, but I do not have such folder on my PC, because I deleted it.

**Comment by Exactol** [comment]
Can you run hammer for the game you want to compile for and then launch compile pal? I think it’s picking up the info for last hammer you launchedOn Jan 21, 2024, at 7:19 AM, SARCASMISH ***@***.***> wrote:﻿
Compile Pal Version
0.28
Describe the bug
Compile Pal crashes instantly on launch.
Steps to reproduce
Run CompilePalX.exe
Expected behavior
I excepted Compile Pal to run normally.
Debug.log
debug.log
Crash logs
2024-01-21T13-05-52.txt
Additional context
It seems that the program can't find GameConfig.txt file in "Half-Life 2 Beta" folder, but I do not have such folder on my PC, because I deleted it.
