### ISSUE TITLE
Hyper threading fail :(

### ISSUE THREAD

**Issue by MrNemersis** [ruarai/CompilePal#29]
Hi. I tryed to compile wia stock hammer editor tools and it's going really slow. In CompilePal it take forever to count how many treads my PC has. After that it's not going anywhere. Anyway i'm not sure if it's any issue just letting you know. Before compile a map disable hyper threading via BIOS.

**Comment by maxdup** [comment]
Interesting. I think this would be an issue with vvis.exe and vrad.exe but if this behavior is only happening inside compilepal then that's definitely weird. Have you experimented with the "-threads" option that's available for vvis and vrad? that option let's you override how many thread are being used so that would skip the counting phase, in theory.

**Comment by MrNemersis** [comment]
Nah. I just launched normal compile to look how light fits and stuff. Then i remembered that hyper threading just slows down compile process. But not completly stops it anyway. So i disabled it and now it's works fine.

**Comment by ruarai** [comment]
I'm guessing this same issue happens with the stock compilation tools, so there's not a huge amount we can do. As maxdup said, the -threads option might be able to help.

If this just happens with Compile Pal though, then it sounds like something that needs investigating.
