### ISSUE TITLE
Error checking in massive quantities causes slowdown

### ISSUE THREAD

**Issue by RevCosmosis** [ruarai/CompilePal#31]
**(Disclaimer: I'm running on version 23 because I'm too lazy to update. Maybe this has already been fixed.)**

I'm getting a lot of "Too many light styles on a face" warnings because of some dynamic lights that I'm not managing very carefully. This warning in particular likes to multiply itself since it feels the need to warn me separately about every individual face that it effects. I'm also compiling nine maps at once, which means that I see this at the end of my compile:

![image](https://vgy.me/xfRkLL.png)

I believe something about the styling or links on these is a little slow, as the compile log window will start running at about 5 seconds per frame (while the rest of the program runs fine).

**Comment by maxdup** [comment]
Thanks for bringing that to our attention. The logging of those error links did change quite a bit in v24 actually, maybe it got worst, maybe it got better. would be neat if you could benchmark that for us.

**Comment by ruarai** [comment]
I've pushed a change that groups errors both by type (so in this case it would say something like 200x of 'too many light styles') and by map (to address maxdup's concern).

I'm not sure that this will completely solve your issue entirely as these errors will still be getting printed all the same during compilation itself. Do you get a slowdown before the end of compilation?

**Comment by RevCosmosis** [comment]
It does slow down before the compile ends. I'll upgrade to 24 and see if the problem persists.

**Comment by ruarai** [comment]
Thanks for the vmf, has been very helpful in my tests so far.

The easy way to fix this would just to prevent hyperlinking of the same error after some reasonable amount of time. I'm not sure this is the approach we want to take though, since logging has slowly become a series of increasingly concerning compromises, since the current RichTextBox we use is not made for this task at all.

So some kind of new log output entirely might be necessary, I'll give it a look soon.

In the meantime, if it's annoying enough, you can replace the errors.txt in the Compiling folder with this: [errors.txt](https://github.com/ruarai/CompilePal/files/1063923/errors.txt). (Although this might be an even more annoying way to address it since Compile Pal will try to re-download the file every 7 days unless you edit it or something.)

**Comment by ruarai** [comment]
I've added a basic form of hyperlink suppression in the latest commit. I haven't totally been able to recreate the performance losses that you describe so if you can, it would be helpful to know if this change helps at all. You can download this [test version](https://github.com/ruarai/CompilePal/files/1067030/Compile.Pal.Test.Version.zip) and let me know if it helps.
