### ISSUE TITLE
Can't pack custom content!

### ISSUE THREAD

**Issue by RealPlanet** [ruarai/CompilePal#36]
Here's the packing process log:

> 

CompilePal - Automated Packaging
Finding sources of game content...
Found search paths...
Found search path: D:\Program Files (x86)\Steam\steamapps\common\left 4 dead 2\update
Found search path: D:\Program Files (x86)\Steam\steamapps\common\left 4 dead 2\left4dead2_dlc3
Found search path: D:\Program Files (x86)\Steam\steamapps\common\left 4 dead 2\left4dead2_dlc2
Found search path: D:\Program Files (x86)\Steam\steamapps\common\left 4 dead 2\left4dead2_dlc1
Found search path: D:\Program Files (x86)\Steam\steamapps\common\left 4 dead 2\hl2
Found search path: D:\Program Files (x86)\Steam\steamapps\common\left 4 dead 2\csgo
Reading BSP...
Something broke:
System.IndexOutOfRangeException: Indice oltre i limiti della matrice.
   in CompilePalX.Compilers.BSPPack.BSP.buildEntityList()
   in CompilePalX.Compilers.BSPPack.BSP..ctor(FileInfo file)
   in CompilePalX.Compilers.BSPPack.BSPPack.Run(CompileContext context)
'Publish' compile finished in 00:00:51
0 errors/warnings logged:
  No errors/warnings logged for meatlocker_c1_a2

The rest of the log has been checked by me and it doesnt not have any problems.
The game is l4d2 and models do work ingame.

**Comment by maxdup** [comment]
To be honest, the packing has never been tested on l4d. Out of curiosity, have you succesfully used compilepal's packing on a l4d project before?
There's not much I can tell you about this error atm. All I know is that compilepal failed to parse the entities from the bsp so it's not a problem with a specific asset. I'm not sure how that could be, are you using l4d's scripting capabilities? I know for sure that compilepal can't really read those scripts, this could be the cause here.

**Comment by RealPlanet** [comment]
It's the first l4d map I ever did tbh, so no never had it working on the game but all other functions seems to be working just fine!
As for scripts,im not using any except ofc the ones that come with the map andare in by default.

**Comment by maxdup** [comment]
finally figured this one out, l4d2 will be supported in v26
