### ISSUE TITLE
add -include and -exclude options for packing

### ISSUE THREAD

**Issue by maxdup** [ruarai/CompilePal#44]
-include: provides a list of assets to be added regardless of detection
-exclude: provides a list of assets or directories to be ignored by packing

**Comment by Exactol** [comment]
I had someone ask me to add this feature, and since this issue has been open for a while I assumed you weren't working on it. 

Right now the current behavior for what I added is for Compile Pal to detect any dependencies of the manually included file and pack them as well, but I'm not sure if that should be the default behavior, since this is kind of a manual override. If anyone thinks it shouldn't do that, feel free to change it.

Something for the future might be to add a option to exclude or include files in a csv file.

**Comment by maxdup** [comment]
Good stuff man, I was going to do it but then real life and stuff. Can't wait to look into what you've done .
